### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by redblindbananaz** [The-Digital-Dilemma/GetIT#23]

**Comment by redblindbananaz** [comment]
We collect personal information from you, including information about your:
name
contact information

We collect your personal information in order to:
identify, authorise and authenticate users

Besides our staff, we share this information with:
no other party in order to .

Providing some information is optional. If you choose not to enter username and password, we'll not being able to provide the viewing of the content for each courses.
We keep your information safe by storing it in a secure way and only accessible by our staff administrators and instructors .

We keep your information for 2 years at which point we securely destroy it by erasing all digital data.
You have the right to ask for a copy of any personal information we hold about you, and to ask for it to be corrected if you think it is wrong. If you’d like to ask for a copy of your information, or to have it corrected, please contact us at Info@GetIT.co.nz.

**Comment by redblindbananaz** [comment]
Please review and comment, simple privacy policy

**Comment by charlie-canning-whitecliffe** [comment]
Looks good adding it now.
