### ISSUE TITLE
Defining user roles and permissions

### ISSUE THREAD

**Issue by redblindbananaz** [The-Digital-Dilemma/GetIT#47]
User registering through web app don't have any permissions to access admin ( Thanks @Maki)
Maybe we could create groups for the administrators (full access) and teachers( view and modify courses?)

**Comment by makikamiya** [comment]
- [ ] 'Administrator' and 'Instructor' user groups have been created.

In conjunction with these user groups I have now created the following features that are accessible only to authorised users belonging to these user groups:

- [ ] Forms have been created that enable course, chapter and lesson details to be edited (Sorry, the form templates have no styling applied at the moment, but they are functional.)
- [ ] Administrators and Instructors will see clickable 'pencil' icons appear on the courses_list page that allows course details to be edited via the corresponding form.
- [ ] Administrators and Instructors will see 'pencil' icons appear on the course_details page that allows chapter and lesson details to be edited via the corresponding forms.
- [ ] Authenticated (logged-in) users who are not in the Administrator or Instructor groups will not see the 'pencil' icons, so should not be able to edit content.
